language: python

matrix:
  include:
    - python: 3.9
      dist: xenial
      sudo: true
    - python: 3.10
      dist: xenial
      sudo: true
    - python: 3.11
      dist: xenial
      sudo: true
    - python: 3.12
      dist: xenial
      sudo: true

install:
  - pip install -r requirements-dev.txt
  - pip install .
script:
  - tox

notifications:
  email:
  - sharpbit3618@gmail.com