os: linux
dist: focal
language: python

python:
  - "3.9"
  - "3.10"
  - "3.11"
  - "3.12"

install:
  - pip install -r requirements-dev.txt
  - pip install .
script:
  - tox

notifications:
  email:
  - sharpbit3618@gmail.com